allowBuilds:
  '@clerk/shared': set this to true or false
  bufferutil: set this to true or false
  core-js: set this to true or false
  msw: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
