allowBuilds:
  '@clerk/shared': true
  bufferutil: false
  core-js: false
  msw: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
